image: maven:3-jdk-8
cache:
  paths:
  - $HOME/.m2/
stages:
- build
- deploy
- see
build:
  stage: build
  script:
  - mvn clean install
  artifacts:
    paths:
    - target/
  only:
  - master
  tags:
    - docker
deploy:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=dispo-prefecture-94 --api-key=$HEROKU_API_KEY
  only:
  - master
  tags:
    - docker
logs:
  stage: see
  script:
  - cp .netrc $HOME/
  - sed -i.bak s/<your-api-key>/$HEROKU_API_KEY/g $HOME/.netrc
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku logs --tail
  only:
  - logs-trigger
  tags:
    - docker