stages:
- build
- deploy
build:
  image: maven:3-jdk-8
  stage: build
  script:
  - mvn clean install
  artifacts:
    paths:
    - target/
  only:
  - master
  tags:
    - docker
  cache:
    paths:
    - $HOME/.m2/
deploy:
  image: ruby:latest
  stage: deploy
  script:
  #- apt-get update -qy
  #- apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=dispo-prefecture-94 --api-key=$HEROKU_API_KEY
  only:
  - master
  tags:
    - docker