image: maven:3-jdk-8
cache:
  paths:
  - $HOME/.m2/
stages:
- build
- deploy
- see
build:
  stage: build
  script:
  - mvn clean install
  artifacts:
    paths:
    - target/
  tags:
    - docker
deploy:
  stage: deploy
  script:
  - gem install dpl
  #- apt-get install dpl
  - dpl --provider=heroku --app=dispo-prefecture-94 --api-key=$HEROKU_API_KEY
  tags:
    - docker
logs:
  stage: see
  script:
  - heroku logs
  tags:
    - docker